sudo: required
os:
- linux
- osx
dist: trusty
language: cpp
compiler:
- gcc
- clang
addons:
  apt:
    sources:
    - george-edison55/cmake-3.x
    packages:
    - cmake
    - libsdl2-dev
    - asciidoc
before_install:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash scripts/travis-osx-setup.sh; fi
script:
    - "mkdir build && cd build && cmake ../ && make && ctest -VV && cd .."
    - "cd docs && ./build-travis.sh && cd .."
